modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"

[[mods]]
modId="howdareyouload"
version="${file.jarVersion}"
displayName="HowDareYouLoad"
authors="Team Potato"
description='''

'''
