modLoader="javafml"
loaderVersion="[36,)"
license="GNU GENERAL PUBLIC LICENSE Version 3"

[[mods]]
modId="howdareyouload"
version="${file.jarVersion}"
displayName="HowDareYouLoad"
authors="Team Potato"
description='''

'''